#!/bin/bash

cd ./lib/cpp_kernel
g++ -std=c++14 -c -fPIC _main.cpp -o MC.o
g++ -shared -Wl,-install_name,MC.so -o MC.so MC.o
cd ..
cd ..
python Airline.py
#python FTSE100.py
#python Nile.py
#python Example.py
